= Betweenness Centrality

_Betweenness Centrality_ is a measure of centrality in a graph based on shortest paths. For every pair of vertices in a connected graph, there exists at least one shortest path between the vertices such that either the number of edges, that the path passes through or the sum of the weights of the edges is minimized. The betweenness centrality for each vertex is the number of these shortest paths, that pass through the vertex.

== History, Explanation

_Betweenness Centrality_ finds wide application in network theory. It represents the degree of which nodes stand between each other. For example, in a telecommunications network, a node with higher betweenness centrality would have more control over the network, because more information will pass through that node. Betweenness centrality was devised as a general measure of centrality. It applies to a wide range of problems in network theory, including problems related to social networks, biology, transport and scientific cooperation.

Although earlier authors have intuitively described centrality as based on betweenness, Freeman (1977) gave the first formal definition of betweenness centrality. The idea was earlier proposed by mathematician J. Anthonisse, but his work was never published.

_Betweenness centrality_, as defined above, is a measure of information control assuming two important hypothesis: 
 
 - every pair of vertices exchange information with equal probability
 
 - information flows along the geodesic (shortest) path between two vertices

However, information not always takes the shortest route. In social network, for instance, a news about a friend of us might not come directly from the friend, but from another mutual friend.

== When to use it / use-cases

It differs from the other centrality measures. A vertex can have quite low degree, be connected to others that have low degree, even be a long way from others on average, and still have high betweenness. Consider a vertex A that lies on a bridge between two groups of vertices within a network. Since any path between nodes in different groups must go through this bridge, node A acquires high betweenness even though it is not well connected (it lies at the periphery of both groups) and hence it might not have particularly high values for degree, eigenvector, and closeness centrality. Vertices in roles like this are sometimes referred to as brokers.

== Constraints / when not to use it

== Algorithm explanation on simple sample graph

[source,cypher]
----
CALL algo.betweennessStream() YIELD nodeId, centrality

CALL algo.betweenness('','', {write:true, stats:true, writeProperty:'centrality'}) 
YIELD nodeCount, minCentrality, maxCentrality, sumCentrality, loadDuration, evalDuration, writeDuration
----

== Example Usage

== References

https://www.sci.unich.it/~francesc/teaching/network/betweeness.html

https://en.wikipedia.org/wiki/Centrality

https://en.wikipedia.org/wiki/Betweenness_centrality


== Implementation Details

:leveloffset: +1
// copied from: https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/98

Calculating _Betweenness_ Centrality for all nodes in a graph involves computing the (unweighted) shortest paths between all pairs of nodes in the graph. A breath-first visit from a source node can be used to compute all shortest paths from the source.

The value of _Betweenness_ Centrality for each vertex is the number of these shortest paths that pass through the vertex.

## Progress

- [ ] adapt apoc-procedure to algorithm-api
- [x] implement procedure
- [x] tests
- [ ] edge case tests
- [ ] simple benchmark 
- [ ] benchmark on bigger graphs
- [ ] parallelization
- [ ] evaluation
- [ ] documentation

## TODO

- adapt apoc-procedure to algorithm-api
